# Generated by Django 4.2 on 2023-08-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image',
            new_name='profile',
        ),
    ]
