# Generated by Django 4.2 on 2023-08-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='k',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
